openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: Documentation for the E-commerce API
servers:
  - url: http://localhost:8080
    description: Local server

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: Pikachu
        price:
          type: number
          example: 10
        category:
          type: string
          example: Electric
        stock:
          type: number
          example: 100
        available:
          type: boolean
          example: true
    Cart:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                example: Product ID
              quantity:
                type: number
                example: 2

paths:
  /api/products:
    get:
      summary: Retrieve a list of products
      tags: [Products]
      responses:
        200:
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      summary: Create a new product
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        201:
          description: The created product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /api/products/{id}:
    delete:
      summary: Delete a product
      tags: [Products]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The product id
      responses:
        200:
          description: The deleted product
        404:
          description: Product not found

  /api/carts:
    get:
      summary: Retrieve a list of carts
      tags: [Carts]
      responses:
        200:
          description: A list of carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'

  /api/carts/{cid}:
    post:
      summary: Add a product to the cart
      tags: [Carts]
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: The cart id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pid:
                  type: string
                  description: The product id
                quantity:
                  type: number
      responses:
        200:
          description: The updated cart

  /api/carts/{cid}/products/{pid}:
    delete:
      summary: Remove a product from the cart
      tags: [Carts]
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: The cart id
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: The product id
      responses:
        200:
          description: The updated cart
